### ISSUE TITLE
Finish Line

### ISSUE THREAD

**Issue by austinorr** [Geosyntec/StormPiper#102]
# This issue tracks todo items to bring this application across the finish line.

## Map improvements
- [x] improve color choices for points and boundaries so they are differentiable from the background.
- [x] display subbasins (vector layer) on the map
- [x] display loading layers from ee on the map via the tile server. This includes runoff volume for 4 epochs, and concentrations for TSS, TN, TP. Confine this to raw layers only, i.e., not load which is the result of conc * volume
- [x] join results table to subbasins and display results as a choropleth for the following:
  - [x] #231
  - [x] load reductions for all epochs for all pollutants

## Scenario Manager
- [x] build a workflow ui for users to build up a _simple_ scenario:
  A simple scenario is defined as: one delineation and one optional structural BMP. 
  Scenarios are not aware of other existing BMPs and are not aggregable to the subbasin scale.
  - a no bmp scenario is useful for determining loading within a boundary. users can multiply that loading by the efficacy of a non-structural BMP to get an off-line estimate of a planned non-structural load reduction performance.
  - scenarios can be given names so that the user can 'combine' multiple BMPs into a total load and effectiveness offline. 
  - [x] build ui for defining a new scenario with a user-drawn delineation (polygon) & BMP (point) with associated BMP modeling parameters
  - [x] build new backend tables for storing the delineations and tmnt facilities with an associated scenario id & name 

## Subbasin Prioritization 
- [x] fetch and display the equity layer
- [x] union the equity layer with the subbasins on the backend, and store new summary stats table in database to be joined
- [x] develop weight scheme for equity metrics and loading (computed after load reductions)
- [x] develop ui for entering weight factors for each measure. 
- [x] group loading weights into runoff volume, sediment, nutrients, metals
- [x] develop functional backend (no memory) calculator for running the user defined prioritization
- [x] develop frontend choropleth datavis for results with ranked summary table with final 'score'.

**Comment by acang-gs** [comment]
### Results Viewer 
- [ ] Fix number formatters in subbasin results table (facility counts rendered as all zeros)
- [ ] Update subbasin results map legend to show field display name instead of id
- [ ] Changed pinned subbasin results table fields to show display name instead of id
- [ ] Fix responsive spacing on results page action cards

**Comment by austinorr** [comment]
bump @acang-gs are these done?

**Comment by acang-gs** [comment]
Done!
