### ISSUE TITLE
Map and component styling 

### ISSUE THREAD

**Issue by cnilsen** [Geosyntec/StormPiper#122]
@acang-gs Here are some suggested improvements for the landing page. What do you think?

### Add additional mapbox basemaps
* [Outdoors](https://api.mapbox.com/styles/v1/mapbox/outdoors-v12.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA#10.32/47.2126/-122.4487)
* [Streets](https://api.mapbox.com/styles/v1/mapbox/streets-v12.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA#10.32/47.2126/-122.4487) 
* [Satellite Streets ](https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v12.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA#10.32/47.2126/-122.4487)

### Add Navigation Controls to the map. 
The map should include navigation buttons. These things: 
<img width="51" alt="image" src="https://user-images.githubusercontent.com/4753248/214196408-d896cad0-dac8-4dfe-a6bc-b1a20d5d03a4.png">

[Here's a Codepen example](https://codepen.io/cnilen79/pen/rNrJEJb)

### Update MUI Components 
The styling of components could make use of MUI styles. I marked up some screen shots with some suggestions for styling. [Link here](https://whimsical.com/9SyerNXmvYyCsv6uGNoCTo). 
For example, here's an idea for styling the layer menu. 
<img width="441" alt="image" src="https://user-images.githubusercontent.com/4753248/214195563-0bd1e726-7e5d-4d81-8dd0-ed7fe93c7dea.png">

**Comment by austinorr** [comment]
@acang-gs bump

**Comment by acang-gs** [comment]
Closed by #275 
Overall, we've adopted a cleaner layer selector and added zoom buttons. No new base layers for now, unless specifically asked for.
