### ISSUE TITLE
Low-Hanging UI Punchlist

### ISSUE THREAD

**Issue by austinorr** [Geosyntec/StormPiper#190]
## Landing Page
- [x]  reorder dropdown nav list order as Map Explorer, Decision Support, Scenario Builder
- [ ]  include secondary color on either the icon or the title text on the card.
- [ ]  link to docs, or add more text/context below the fold.

## Nav
- [x] User Profile  and Main dropdown navs are stealing scroll. fix so they don't show/hide scroll bar.

## user profile dropdown pages
- [x] add "Manage Users" title to card above table. match cost settings style
- [x] style "Profile" title same as 'Cost Settings' title. standardize throughout site.

## Map Explorer
- [x] BMP Stats PopUp needs more BMP info. @christian to include required fields here:
  - Tacoma Type
  - BMP Type
  - ...
- [x] results table
  - this should likely move to new page, rather than full-screen slide over. then we can add to it, add exporters, let users open two tabs, etc.
  - add selector for epochs including 'all'

## BMP Detail Page
- [x] drop delin editor card
- [ ]

**Comment by acang-gs** [comment]
### Cross Browser Issues

- [ ] Fix side drawer issue in Safari (drawer cuts off after button list)

**Comment by acang-gs** [comment]
- [ ] Link node id's from facility result viewer to bmp detail page (steal scenario viewer pattern, use Link components and not useNavigate)
- [ ] Add subbasin map and chloropleths to subbasin results viewer page (steal prioritization pattern)
