### ISSUE TITLE
Cannot edit parameters for flow duration facilities. 

### ISSUE THREAD

**Issue by cnilsen** [Geosyntec/StormPiper#283]
Tried to edit a bioretention facility and convert it to a Flow Duration tank. I fill out all parameters. 

On save, the error provided is: 

Error Saving BMP 
1 validation error 
media_filtration_rate_inhr field required

**Comment by austinorr** [comment]
@acang-gs looks like this is in the front end form validation, not the backend. it happens before any patch request is sent to the backend.
