### ISSUE TITLE
Identify basins that are performing street sweeping and line cleaning 

### ISSUE THREAD

**Issue by cnilsen** [Geosyntec/StormPiper#58]

**Comment by cnilsen** [comment]
<img width="510" alt="Thea Foss " src="https://user-images.githubusercontent.com/4753248/192659550-1f573ecc-089f-4c32-925c-2ca957db5dbc.png">
These basins have street sweeping and line cleaning.

**Comment by austinorr** [comment]
@cnilsen no other subbasins have either sweeping or line cleaning then. only thea foss for both? Last time after i declared FOSS! you said "wait, there's more" so this really is 100 of all source controls in tacoma at the current time. ok!
