### ISSUE TITLE
Add is_dirty notification and rpc_solve feature

### ISSUE THREAD

**Issue by acang-gs** [Geosyntec/StormPiper#59]
As a user wanting to make changes to my existing BMP features, I select a tmnt facility, edit its attributes, and submit them. I will then receive a notification that indicates that the current performance results are out of date. This notification will give me the option of recalculating so that I can have fresh results.

**We need two new features:**

**Receive is_dirty notification:**

- Display a button on either the top menu or side, which is disabled when results are not dirty
- Poll the `api/rest/results/is_dirty` endpoint on a regular interval, and read the `is_dirty` property, and compare the last updated time to a cached time. If the cached time is older than the response time, then we know that we are out of date 
- If the database is dirty, then we need to recalculate. If our update times are out of sync, then we need to fetch updated results tables (i.e. don't need to recalculate)
- If we are out of date, update the application state and enable the button

**Present a feature that will recalculate results:**

- When the button is enabled, the user clicks the button and presents a dialog that explains that results are out of date and presents a button that will recalculate results 
- When the recalculate button is clicked, hit the `api/rpc/solve_watershed` endpoint 
- Poll the `is_dirty` endpoint until we see that is_dirty is false, then present a success message, and update the application state to show that results are up to date

**Comment by austinorr** [comment]
@acang-gs ready to close?
