### ISSUE TITLE
Determine Final Reference Layers - vector

### ISSUE THREAD

**Issue by austinorr** [Geosyntec/StormPiper#89]
Thin the list and identify specific layers and _why_ they are needed - christian
 - contextual information? this goes to Adrian.
 - calculable information? this goes to Austin

**Comment by cnilsen** [comment]
Closing - will move to the datastudio model

**Comment by austinorr** [comment]
@cnilsen i don't know if datastudio can help us with this... our webmap can not be an iframe.

**Comment by cnilsen** [comment]
It doesn't need to be. Can it embed an idea me with the results? I've figured out how to pass parameters through the url.

**Comment by austinorr** [comment]
@cnilsen let’s wait and  discuss, the backend is already serving the results correctly.

**Comment by austinorr** [comment]
> Closing - will move to the datastudio model

@cnilsen Reopening - this issue is meant to track improvements to the existing webmap, so data studio likely cannot/should not help us here, unless we want to direct users to a fully separate page to review reference layers. My take is that we do not want to do this, we want to be able to present things in one map.

Data studio can do useful isolated embeds, but we should limit its use only to things that are not easy with our current system, like the land use summary you demoed.

**Comment by cnilsen** [comment]
@austinorr Here's the list of layers to add. I will get the tileserver layers up. The vectors should be added to the webmap, but if they are too big, we can tile them. 
[final layers to add.xlsx](https://github.com/Geosyntec/StormPiper/files/9965805/final.layers.to.add.xlsx)

**Comment by austinorr** [comment]
@acang-gs please work with @cnilsen to find these geojson web endpoints. You might have some of these already, but this is the list of layers we want.
bmp locations, watersheds, subbasins (watersheds and subbasins are the same layer), and bmp delineations are all served by the backend already. the others are just for reference.
